const enTranslations = {
    ACCOUNT_USER_ALREADY_EXISTS: 'Account with this username already exists.',
    ACCOUNT_TOO_SHORT_USER_NAME: 'To short username. Should be 5 chars at least.',
    LOGIN: 'Login',
    SIGNUP: 'Signup',
    LOGOUT: 'Logout',
    TEXT_LOGIN: 'If you want to login, click',
    TEXT_SIGNUP: 'If you want to signup, click',
    HERE: 'HERE',
    USERNAME_PLACEHOLDER: 'Username',
    IS_NOT_PASSWORD: '[@TODO] Password must be at least 5 chars long, has at least one lower and one upper case, one special char and min one number',
    PASSWORD_PLACEHOLDER: 'Password',
    OVERLAY_TITLE: 'Hello, Friend',
    OVERLAY_SUBTITLE: 'Enter your personal details and start journey with dragon program',
    NEW_DRAGON: 'New Dragon',
    DRAGON_STACK: 'Dragon Stack',
    GENERATION: 'Generation',
    DATA: 'Express on',
    ACCOUNT_DRAGON: 'Your dragons',
    NAME: 'Name',
    VALUE: 'Value',
    DRAGONS: 'Dragons',
    DRAGON_NAME: 'Dragon Name',
    DRAGON_ID: 'Dragon Id',
    DRAGON_IMAGE: 'Dragon Image',
    DRAGON_TRAITS: 'Dragon Traits',
    SALE_VALUE: 'Sale Value',
    SIRE_VALUE: 'Sire Value',
    PUBLIC: 'Public',
    EDIT: 'Edit',
    SAVE: 'Save',
    DRAGON_PUBLIC: 'Public dragons ',
    BUY: 'Buy',
    SIRE: 'Sire',
    TEXT: 'Pick one of your dragons to mate with',
    HOME: 'Home',
    BALANCE: 'Balance',
    ORANGE: 'orange',
    PINK: 'pink',
    GREEN: 'green',
    BLUE: 'blue',
    SPORTY: 'sporty',
    SKINNY: 'skinny',
    STOCKY: 'stocky',
    SLENDER: 'slender',
    PLAIN: 'plain',
    STRIPED: 'striped',
    SPOTTED: 'spotted',
    PATCHY: 'patchy',
    BIG: 'big',
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
    NEW_GENERATION: 'New Generation',
    WRITE: 'Here you can write name',
    CHOOSE: 'Here you can choose',
    WRITE_VALUE: 'Here you can write value',
    NO_DRAGONS: 'You have no dragons',
    USERNAME_OR_PASS_INCORRECT: 'Username or password is incorrect',
    OPEN_POPUP: 'Do you want to know more about this program? Click',
    DRAGONS_PROGRAM: 'Dragons program',
    TEXT_POPUP: 'In the Dragon App you can create your account and select a dragon with different values. You can have more dragons on your account, edit them and add them to public ones. In the Public tab, you will find all public dragons that you can buy or breed.',
    CLOSE: 'Close',
    TITLE: 'Welcome in',
    SUBTITLE: 'Dragon Program',
    AUTH_FORM: 'Create Account',
    ABOUT: 'About Program',
    TEXT_ABOUT: 'In the Dragon program, you create your own account and manage your Dragons. You can spend 50 Euro to buy dragons. You can add and edit a Dragon. Then you can make one of your Dragons public and multiply. You also have the option of translating the text into different languages.',
    TEXT_LOGIN_FORM: 'On the Login page you will find the login Form and sign up for the Dragon program.',
    TEXT_HOME: 'In the Home tab you can add a new Dragon with individual values.',
    TEXT_DRAGONS: 'In the Dragons tab, after clicking the button, you can edit and make your Dragons public.',
    TEXT_PUBLIC: 'In the Public tab you can buy and breed your Dragons.'
}

const plTranslations = {
    ACCOUNT_USER_ALREADY_EXISTS: 'Konto z takim uzytkowniekiem juz istnieje.',
    ACCOUNT_TOO_SHORT_USER_NAME: 'Za krotka nazwa. Powinno być 5 znaków najmniej.',
    LOGIN: 'Zaloguj się',
    SIGNUP: 'Zarejestruj się',
    LOGOUT: 'Wyloguj się',
    TEXT_LOGIN: 'Jeśli chcesz się zalogować, kliknij',
    TEXT_SIGNUP: 'Jeśli chcesz się zarejestrować, kliknij',
    HERE: 'TUTAJ',
    USERNAME_PLACEHOLDER: 'Nazwa użytkownika',
    IS_NOT_PASSWORD: '[@TODO]Wpisz hasło.',
    PASSWORD_PLACEHOLDER: 'Hasło',
    OVERLAY_TITLE: 'Witaj, przyjacielu!',
    OVERLAY_SUBTITLE: 'Wprowadź swoje dane osobowe i rozpocznij podróż z programem smoka',
    NEW_DRAGON: 'Nowy dragon',
    DRAGON_STACK: 'Generacja smoka',
    GENERATION: 'Generacja',
    DATA: 'Data',
    ACCOUNT_DRAGON: 'Twoje smoki',
    NAME: 'Nazwa',
    VALUE: 'Wartość',
    DRAGONS: 'Smoki',
    DRAGON_NAME: 'Nazwa smoka',
    DRAGON_ID: 'ID smoka',
    DRAGON_IMAGE: 'Zdięcie smoka',
    DRAGON_TRAITS: 'Cechy smoka',
    SALE_VALUE: 'Wartość sprzedaży',
    SIRE_VALUE: 'Wartość rozmnożenia',
    PUBLIC: 'Publiczne',
    EDIT: 'Edytuj',
    SAVE: 'Zapisz',
    DRAGON_PUBLIC: 'Publiczne smoki',
    BUY: 'Kup',
    SIRE: 'Rozmnożenie',
    TEXT: 'Wybierz jednego ze swoich smoków do rozmnożenia',
    PAGES: 'Pages',
    HOME: 'Strona główna',
    BALANCE: 'Saldo',
    ORANGE: 'pomarańczowy',
    PINK: 'różowy',
    GREEN: 'zielony',
    BLUE: 'niebieski',
    SPORTY: 'sportowy',
    SKINNY: 'chudy',
    STOCKY: 'krępy',
    SLENDER: 'smukły',
    PLAIN: 'zwykły',
    STRIPED: 'paski',
    SPOTTED: 'cętkowany',
    PATCHY: 'niejednolity',
    BIG: 'duży',
    SMALL: 'mały',
    MEDIUM: 'średni',
    LARGE: 'wielki',
    NEW_GENERATION: 'Nowa generacja',
    WRITE: 'Tu możesz wpisać nazwę',
    CHOOSE: 'Tu możesz wybrać',
    WRITE_VALUE: 'Tu możesz wpisać wartość',
    NO_DRAGONS: 'Nie masz smoków',
    USERNAME_OR_PASS_INCORRECT: 'Nieprawidłowa nazwa użytkownika lub hasło',
    OPEN_POPUP: 'Chcesz wiedziec wiecej o tym programie? Kliknij',
    DRAGONS_PROGRAM: 'Program smoki',
    TEXT_POPUP: 'W Aplikacji Dragon możesz założyć swoje konto i wybrać smoka z różnymi wartościami. Możesz na swoim koncie mieć więcej smoków, edytować je i dodawać do publicznych. W Public zakładce, znajdziesz wszystkie publiczne smoki, które możesz kupić lub rozmnożyć.',
    CLOSE: 'Zamknij',
    TITLE: 'Witaj w',
    SUBTITLE: 'Programie smoków',
    AUTH_FORM: 'Załóż konto!',
    ABOUT: 'O programie',
    TEXT_ABOUT: 'W programie Smoka zakładasz własne konto i zarządzasz swoimi Smokami. Do kupna smoków masz możliwość wykorzystania 50 Euro. Możesz dodać i edytować Smoka. Następnie możesz któregoś ze swoich Smoków upublicznić i rozmnożyć.',
    TEXT_LOGIN_FORM: 'Na stronie Logowania znajdziesz formularz logowania i zapisania się do programu Smoka.',
    TEXT_HOME: 'W zakładce Home możesz dodać nowego Smoka z poszczególnymi wartościami.',
    TEXT_DRAGONS: 'W zakładce Dragons, po kliknięciu buttona, możesz edytować i upublicznić swoje Smoki.',
    TEXT_PUBLIC: 'W zakładce Public możesz kupić i rozmnożyć swoje Smoki.'
}

const deTranslations = {
    ACCOUNT_USER_ALREADY_EXISTS: 'Ein Konto bei diesem Benutzer ist bereits vorhanden.',
    ACCOUNT_TOO_SHORT_USER_NAME: 'Der Name ist zu kurz. Es sollten mindestens 5 Zeichen vorhanden sein.',
    LOGIN: 'Anmelden',
    SIGNUP: 'Registrieren',
    LOGOUT: 'Ausloggen',
    TEXT_LOGIN: 'Wenn Sie sich anmelden möchten, klicken Sie auf',
    TEXT_SIGNUP: 'Wenn Sie sich registrieren möchten, klicken Sie auf',
    HERE: 'HIER',
    USERNAME_PLACEHOLDER: 'Nutzername',
    IS_NOT_PASSWORD: '[@TODO - transalte from english]Geben Sie das Passwort ein.',
    PASSWORD_PLACEHOLDER: 'Passwort',
    OVERLAY_TITLE: 'Hallo, Freund!',
    OVERLAY_SUBTITLE: 'Geben Sie Ihre persönlichen Daten ein und beginnen Sie die Reise mit dem Drachenprogramm',
    NEW_DRAGON: 'Neuer Drache',
    DRAGON_STACK: 'Drachenstempel',
    GENERATION: 'Generation',
    DATA: 'Daten',
    ACCOUNT_DRAGON: 'Deine Drachen',
    NAME: 'Name',
    VALUE: 'Wert',
    DRAGONS: 'Drachen',
    DRAGON_NAME: 'Drachenname',
    DRAGON_ID: 'Dragon ID',
    DRAGON_IMAGE: 'Zieh den Drachen aus',
    DRAGON_TRAITS: 'Drachenmerkmale',
    SALE_VALUE: 'Verkaufswert',
    SIRE_VALUE: 'Wert Zuchthengst',
    PUBLIC: 'Öffentlich',
    EDIT: 'Bearbeiten',
    SAVE: 'Speichern',
    DRAGON_PUBLIC: 'Öffentliche Drachen',
    BUY: 'Kaufen',
    SIRE: 'Zuchthengst',
    TEXT: 'Wähle einen deiner Drachen aus, um dich zu paaren',
    HOME: 'Hauptseite',
    BALANCE: 'Balance',
    ORANGE: 'Orange',
    PINK: 'Rosa',
    GREEN: 'Grün',
    BLUE: 'Blau',
    SPORTY: 'sport',
    SKINNY: 'dünn',
    STOCKY: 'untersetzt',
    SLENDER: 'schlank',
    PLAIN: 'normal',
    STRIPED: 'gestreift',
    SPOTTED: 'entdeckt',
    PATCHY: 'lückenhaft',
    BIG: 'groß',
    SMALL: 'klein',
    MEDIUM: 'durchschnittlich',
    LARGE: 'enorm',
    NEW_GENERATION: 'Neu Generation',
    WRITE: 'Hier können Sie schreiben Name',
    CHOOSE: 'Hier können Sie wählen',
    WRITE_VALUE: 'Hier können Sie einen Wert eingeben',
    NO_DRAGONS: 'Du hast keine Drachen',
    USERNAME_OR_PASS_INCORRECT: 'Ungültiger Benutzername oder Passwort',
    OPEN_POPUP: 'Möchten Sie mehr über dieses Programm erfahren? Klicke',
    DRAGONS_PROGRAM: 'Das Drachenprogramm',
    TEXT_POPUP: 'In der Drachen-App können Sie Ihr Konto erstellen und einen Drachen mit unterschiedlichen Werten auswählen. Sie können weitere Drachen in Ihrem Konto haben, diese bearbeiten und öffentlichen hinzufügen. Auf der Registerkarte Öffentlich finden Sie alle öffentlichen Drachen, die Sie kaufen oder züchten können.',
    CLOSE: 'Schließen',
    TITLE: 'Willkommen zu',
    SUBTITLE: 'Drachenprogramm',
    AUTH_FORM: 'Konto Erstellen!',
    ABOUT: 'Über das Programm',
    TEXT_ABOUT: 'Im Dragon-Programm erstellen Sie Ihr eigenes Konto und verwalten Ihre Drachen. Sie können 50 Euro ausgeben, um Drachen zu kaufen. Sie können einen Drachen hinzufügen und bearbeiten. Dann können SIe einen deiner Drachen öffentlich machen und multiplizieren. Sie haben auch die Möglichkeit, den Text in verschiedene Sprachen zu übersetzen.',
    TEXT_LOGIN_FORM: 'Auf der Anmeldeseite finden Sie das Anmeldeformular und können sich für das Dragon-Programm anmelden.',
    TEXT_HOME: 'Auf der Registerkarte Home können Sie einen neuen Drachen mit individuellen Werten hinzufügen.',
    TEXT_DRAGONS: 'Auf der Registerkarte Drachen können Sie nach dem Klicken auf die Schaltfläche Ihre Drachen bearbeiten und öffentlich machen.',
    TEXT_PUBLIC: 'Auf der Registerkarte Öffentlich können Sie Ihre Drachen kaufen und züchten.'
}

const translations = {
    en: enTranslations,
    pl: plTranslations,
    de: deTranslations
};

export {translations}
